# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(max_length=200),
        ),
    ]
